### ISSUE TITLE
There is no manual :(

### ISSUE THREAD

**Issue by lostinblue** [kintoandar/rtfm#1]
Can you explain what this is? I'm working on something similar I believe. This is for setting up a system with coreboot and minimal compartmentalized setup?

**Comment by kintoandar** [comment]
Hey,

This repo is just for my personal use, as you can see on the `README.md`, it was not built to be maintained. That said, you're welcome to use any of its components.

In a nutshell, these are the configurations for a machine install system using PXE + TFTP + DHCPD + Kickstarts for a complete "cloud" base install.

All the configs are fully working, if that helps you.

Have fun!
